version: '3'

services:
  db:
    image: mariadb:latest
    ports: ["3306:3306"]
    environment:
     - MYSQL_ROOT_PASSWORD=Passw0rd
     - MYSQL_USER=rms
     - MYSQL_PASSWORD=rms
     - MYSQL_DATABASE=rmsdb